name: Verify Dynamic Pages is On for Published Content

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check Dynamic Pages
      run: grep "dynamic_pages\s=\sTrue" pavement.py
